<?php
return array(
    'share' => array(
        'status'=> '1',
        'from'	=> 'share',
        'show'	=> '在线云播',
        'des'	=> '',
        'sort'	=> '17',
        'tip'	=> '/share/',
    ),
    '27pan' => array(
        'status'=> '1',
        'from'	=> '27pan',
        'show'	=> '27盘解析',
        'des'	=> '//www.luwayo.com/vip/?url=',
        'sort'	=> '16',
        'tip'	=> '27pan',
    ),
    'pltv' => array(
        'status'=> '1',
        'from'	=> 'pltv',
        'show'	=> '阿里PLTV',
        'des'	=> 'asset/fed/player.php?id=live&url=',
        'sort'	=> '15',
        'tip'	=> 'PLTV',
    ),
    'rtmp' => array(
        'status'=> '1',
        'from'	=> 'rtmp',
        'show'	=> '阿里RTMP',
        'des'	=> 'asset/fed/player.php?id=live&url=',
        'sort'	=> '14',
        'tip'	=> 'rtmp:',
    ),
    'flv' => array(
        'status'=> '1',
        'from'	=> 'flv',
        'show'	=> '阿里FLV',
        'des'	=> 'asset/fed/player.php?id=live&url=',
        'sort'	=> '13',
        'tip'	=> '.flv',
    ),
    'mp4' => array(
        'status'=> '1',
        'from'	=> 'mp4',
        'show'	=> 'MP4点播',
        'des'	=> 'asset/fed/player.php?id=m3u8&url=',
        'sort'	=> '12',
        'tip'	=> '.mp4',
    ),
    'm3u8' => array(
        'status'=> '1',
        'from'	=> 'm3u8',
        'show'	=> '在线播放',
        'des'	=> 'asset/fed/player.php?id=peer&url=',
        'sort'	=> '11',
        'tip'	=> '.m3u8',
    ),
    'alicdn' => array(
        'status'=> '1',
        'from'	=> 'alicdn',
        'show'	=> '阿里云播',
        'des'	=> 'asset/fed/player.php?id=live&url=',
        'sort'	=> '10',
        'tip'	=> '.alicdn.com',
    ),
    'kankan' => array(
        'status'=> '1',
        'from'	=> 'kankan',
        'show'	=> '看看解析',
        'des'	=> '//jx.58588885.com/?url=',
        'sort'	=> '09',
        'tip'	=> '.kankan.com',
    ),
    'migu' => array(
        'status'=> '1',
        'from'	=> 'migu',
        'show'	=> '咪咕解析',
        'des'	=> '//jx.618g.com/?url=',
        'sort'	=> '08',
        'tip'	=> '.miguvideo.com',
    ),
    'pptv' => array(
        'status'=> '1',
        'from'	=> 'pptv',
        'show'	=> 'PPTV解析',
        'des'	=> '//jx.itaoju.top/?url=',
        'sort'	=> '07',
        'tip'	=> '.pptv.com',
    ),
	'le' => array(
        'status'=> '1',
        'from'	=> 'le',
        'show'	=> '乐视解析',
        'des'	=> '//beaacc.com/api.php?url=',
        'sort'	=> '06',
        'tip'	=> '.le.com',
    ),
    'sohu' => array(
        'status'=> '1',
        'from'	=> 'sohu',
        'show'	=> '搜狐解析',
        'des'	=> '//api.bbbbbb.me/jx/?url=',
        'sort'	=> '05',
        'tip'	=> '.sohu.com',
    ),
    'mgtv' => array(
        'status'=> '1',
        'from'	=> 'mgtv',
        'show'	=> '芒果解析',
        'des'	=> '//jiexi.071811.cc/jx.php?url=',
        'sort'	=> '04',
        'tip'	=> '.mgtv.com',
    ),
    'iqiyi' => array(
        'status'=> '1',
        'from'	=> 'iqiyi',
        'show'	=> '奇艺解析',
        'des'	=> '//jqaaa.com/jx.php?url=',
        'sort'	=> '03',
        'tip'	=> '.iqiyi.com',
    ),
    'youku' => array(
        'status'=> '1',
        'from'	=> 'youku',
        'show'	=> '优酷解析',
        'des'	=> '//jqaaa.com/jx.php?url=',
        'sort'	=> '02',
        'tip'	=> '.youku.com',
    ),
    'qq' => array(
        'status'=> '1',
        'from'	=> 'qq',
        'show'	=> '腾讯解析',
        'des'	=> '//jqaaa.com/jx.php?url=',
        'sort'	=> '01',
        'tip'	=> 'v.qq.com',
    ),
);
?>